### ISSUE TITLE
Performance issues in At a glance page, Absence management page, payslip page

### ISSUE THREAD

**Issue by karthmoh** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#23] opened 2016-12-12 10:09 UTC
Remove the worklist items and recheck the performance

**Comment by SowjanyaDudipalla** [comment] 2016-12-14 06:54
Requested trace file for Absence Management page to check performance.

**Comment by karthmoh** [comment] 2016-12-15 10:35
Workflow Performance issue - bad performing query.

SELECT XMLELEMENT ("actions" ,XMLATTRIBUTES ('true' AS "json:force-array" ,
  'http://json.org/' AS "xmlns:json") ,XMLAGG (XMLELEMENT ("action" ,
  XMLFOREST (WL.LOOKUP_CODE "id" ,WL.MEANING "title" ,'DELETE' "operation" ,
  'true' "bulkActionEnabled" ,XXAS_COM_REST_UTIL_PKG.URI_FROM_PATH 
  ('workflow-notifications/' || WL.LOOKUP_CODE) "href" ) ,XMLELEMENT ("meta" ,
  XMLELEMENT ("options" ,XMLFOREST 
  (XXAS_COM_WORKLIST_PKG.GET_RESPONSE_COLOR_HTML5 (:B1 , WL.LOOKUP_CODE, 
  WL.MEANING, 'COLOR') AS "color" ,
  XXAS_COM_WORKLIST_PKG.GET_RESPONSE_COLOR_HTML5 (:B1 , WL.LOOKUP_CODE, 
  WL.MEANING, 'WEIGHT') AS "weight" ) ) ) ) ORDER BY WL.SEQ ) ) 
FROM
 (SELECT LOOKUP_CODE ,MEANING ,-1 SEQ FROM WF_LOOKUPS WHERE LOOKUP_TYPE = :B1 
  UNION SELECT :B3 LOOKUP_CODE ,
  XXAS_COM_MSG_PKG.GET_STRING('XXAS_RB_COM_CLOSE') MEANING ,-1 SEQ FROM 
  WF_NOTIFICATIONS WF WHERE :B1 IS NULL AND WF.NOTIFICATION_ID = :B2 AND 
  WF.MORE_INFO_ROLE IS NULL) WL


call     count       cpu    elapsed       disk      query    current        rows
------- ------  -------- ---------- ---------- ---------- ----------  ----------
Parse        1      0.00       0.00          0          0          0           0
Execute   2692      0.07       0.08          0          0          0           0
Fetch     2692      4.16       4.25          0      10768          0        2692
------- ------  -------- ---------- ---------- ---------- ----------  ----------
total     5385      4.23       4.34          0      10768          0        2692

Misses in library cache during parse: 0
Optimizer mode: ALL_ROWS
Parsing user id: 86     (recursive depth: 1)
Number of plan statistics captured: 1

Rows (1st) Rows (avg) Rows (max)  Row Source Operation
---------- ---------- ----------  ---------------------------------------------------
         1          1          1  SORT GROUP BY (cr=282 pr=0 pw=0 time=8206 us)
         1          1          1   VIEW  (cr=8 pr=0 pw=0 time=539 us cost=8 size=8092 card=4)
         1          1          1    SORT UNIQUE (cr=8 pr=0 pw=0 time=537 us cost=8 size=146 card=4)
         1          1          1     UNION-ALL  (cr=8 pr=0 pw=0 time=527 us)
         0          0          0      TABLE ACCESS BY INDEX ROWID WF_LOOKUPS_TL (cr=0 pr=0 pw=0 time=3 us cost=3 size=138 card=3)
         0          0          0       INDEX RANGE SCAN WF_LOOKUPS_TL_PK (cr=0 pr=0 pw=0 time=1 us cost=2 size=0 card=3)(object id 205552)
         1          1          1      FILTER  (cr=4 pr=0 pw=0 time=11 us)
         1          1          1       TABLE ACCESS BY INDEX ROWID WF_NOTIFICATIONS (cr=4 pr=0 pw=0 time=9 us cost=3 size=8 card=1)
         1          1          1        INDEX UNIQUE SCAN WF_NOTIFICATIONS_PK (cr=3 pr=0 pw=0 time=5 us cost=2 size=0 card=1)(object id 205567)

********************************************************************************

**Comment by duncancasemore** [comment] 2016-12-15 11:47
Please also see ApplaudSolutions/ebiz#999

**Comment by karthmoh** [comment] 2016-12-26 09:41
Performance issue with Worklist notifications are tracked through #31 . Closing this item

**Comment by asinghmdcbms** [comment] 2016-12-26 10:25
I guess this SR was for tracking performance issue related to (1) At a glance page (2) Absence management page (3) Payslip.

Then why are we closing this issue as a duplicate of bug which tracks  only 'performance related to worklist notifications' ?

**Comment by karthmoh** [comment] 2016-12-26 10:37
The issue related to 
1. At a glance page is because of the Worklist block. After removing the block, the performance is fine.
2. Absence management, the performance is same in both Flash and HTML5. So, during the recent demo on verifying the the Flash version in PROD the performance is good. So, it was decided to take a call on the performance in Absence Management page after the patch is applied on PROD.
3. With regards to Payslip page - we had performance issues earlier, but now the performance is fine. Please note we did not do any action on it.

**Comment by asinghmdcbms** [comment] 2016-12-26 10:40
That a lot for providing closure explanation on all the above points.

**Closed by asinghmdcbms** 2016-12-26 10:40 UTC
