### ISSUE TITLE
Need to press Sign-In button twice on login page in Mobile device

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#63] opened 2017-01-10 09:05 UTC
Need to press Sign-In button twice on login page in Mobile device before home page gets displayed.

I tried on my iPad. Also a couple of users got the same behavior when they used their mobile

**Comment by karthmoh** [comment] 2017-01-10 09:25
Closing this as duplicate of #60. our development team is reviewing this issue.

**Closed by karthmoh** 2017-01-10 09:25 UTC
Labels: bug
