### ISSUE TITLE
Getting error when opening native app

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#35] opened 2016-12-26 06:43 UTC
As per instruction mentioned on http://docs.applaudsolutions.com/quick-start, after launching the app we entered the below URL in the app : http://crp2.pp.mdcbms.ae:8010 . However after the app is launching we are getting below error on my iPad :-

![image](https://cloud.githubusercontent.com/assets/23504285/21477102/103b1fc0-cb58-11e6-8c43-53768b002efb.png)

Please note using browser I am able to access the html5 employeecenter successfully from my iPad.

**Comment by hgajula-applaud** [comment] 2016-12-26 06:59
Amit, You have requested us to provide the app with the url binded . See git #25 . We are still working on this. You can test this when it is ready.

**Comment by hgajula-applaud** [comment] 2016-12-26 09:10
closing this a duplicate of #25

**Closed** 2017-01-08 13:11 UTC
Labels: bug
